// import { getVenueDetails } from "../../actions/order";

// const messages = {
//   sign_in: "εγγραφείτε στα αγγλικά",
//   staying_at_the_hotel: "Διαμονή στο ξενοδοχείο",
//   view_menu: "Προβολή μενού",
//   order_now: "Παράγγειλε τώρα",
//   room: "ΔΩΜΑΤΙΟ",
//   table: "ΤΡΑΠΕΖΙ",
//   password: "ΚΩΔΙΚΟΣ ΠΡΟΣΒΑΣΗΣ",
//   open_or_join_tab: "Άνοιγμα ή συμμετοχή σε μια καρτέλα",
//   read_only_mode: "Λειτουργία μόνο για ανάγνωση",
//   venue_currently_not_accepting_orders: "Ο χώρος δεν δέχεται παραγγελίες προς το παρόν",
//   share: "Μερίδιο",
//   exit_tab: "Καρτέλα εξόδου",
//   join_tab: "Εγγραφή στην καρτέλα",
//   open_tab: "Άνοιγμα καρτέλας",
//   welcome: "καλως ΗΡΘΑΤΕ",
//   join_an_existing_tab_or_open_a_new_one:
//     "Εγγραφείτε σε μια υπάρχουσα καρτέλα ή ανοίξτε μια νέα.",
//   just_having_a_quick_drink_Select_Order_pay_now:
//     "απλά πίνοντας ένα γρήγορο ποτό; Επιλέξτε Παραγγελία & πληρωμή τώρα",
//   open_new_tab: "Άνοιγμα νέας καρτέλας",
//   order_pay_now: "Παραγγελία & πληρωμή τώρα",
//   Join_tab: "Εγγραφή στην καρτέλα",
//   you_do_not_have_any_unpaid_orders: "Δεν έχετε παραγγελίες χωρίς πληρωμή.",
//   Back: "Πίσω",
//   noImg: "όχι Img",
//   My_orders: "Οι παραγγελίες μου",
//   Get_bill: "Λάβετε λογαριασμό",
//   Call_server: "Διακομιστής κλήσεων",
//   No_items_Available: "Δεν υπάρχουν διαθέσιμα αντικείμενα",
//   Powered_by_Blend: "Με την υποστήριξη του Blend",
//   No_available_items: "Δεν υπάρχουν διαθέσιμα αντικείμενα",
//   Add_Blend_Menu_To_Home_Screen: "Προσθήκη μενού μείγματος στην αρχική οθόνη",
//   Url_Not_Found: "Η διεύθυνση URL δεν βρέθηκε",
//   Enter: "Εισαγω",
//   First_Name: "Ονομα",
//   Table_Number: "Αριθμός πίνακα",
//   Last_Name: "Επίθετο",
//   Open_tab: "Ανοίξτε την καρτέλα",
//   Enter_here: "Μπείτε εδώ",
//   Cancel: "Ματαίωση",
//   Join: "Συμμετοχή",
//   Password: "Κωδικός πρόσβασης",
//   Table: "Τραπέζι",
//   Home: "Σπίτι",
//   Error_404: "Σφάλμα 404",
//   Page_Not_Found: "Η σελίδα δεν βρέθηκε",
//   check_it_out: "Τσέκαρέ το",
//   logo: "λογότυπο",
//   no_items_found: "δεν βρέθηκαν αντικείμενα",
//   Choose_type: "Επιλέξτε τύπο",
//   Required: "Απαιτείται",
//   Not_more_than_1: "Όχι περισσότερο από 1",
//   Note: "Σημείωση",
//   Leave_a_note: "Αφήστε ένα σημείωμα",
//   Total: "Σύνολο",
//   Update_order: "Ενημέρωση παραγγελίας",
//   Add_to_order: "Προσθήκη στην παραγγελία",
//   Your_order: "Παραγγελία σας",
//   Room: "Δωμάτιο",
//   Select: "Επιλέγω",
//   Number: "Αριθμός",
//   Order_Note: "Σημείωση παραγγελίας",
//   Leave_a_note_for_the_server: "Αφήστε μια σημείωση για τον διακομιστή",
//   Payment_Status: "Κατάσταση πληρωμής",
//   accepted: "αποδεκτό",
//   only: "μόνο",
//   Add_to_tab: "Προσθήκη στην καρτέλα",
//   Cash: "Μετρητά",
//   Card: "Κάρτα",
//   Pay_now: "Πλήρωσε τώρα",
//   Tip_Server: "Tip Server",
//   other: "άλλα",
//   Not_Now: "Οχι τώρα",
//   Subtotal: "ΜΕΡΙΚΟ ΣΥΝΟΛΟ",
//   Tip: "Υπόδειξη",
//   Total: "Σύνολο",
//   incl_VAT: "συμπεριλαμβανομένου ΦΠΑ",
//   Place_Order: "Παραγγέλνω",
//   Order_Note: "Σημείωση παραγγελίας",
//   Subtotal: "ΜΕΡΙΚΟ ΣΥΝΟΛΟ",
//   Amount_to_tip: "Ποσό ως συμβουλή",
//   Add_tip: "Προσθέστε συμβουλή",
//   Cancel: "Ματαίωση",
//   Would_you_like_to_call_a: "Θα θέλατε να καλέσετε ένα",
//   server: "υπηρέτης",
//   Yes: "Ναί",
//   Ok: "Εντάξει",
//   How_would_you_like: "Πως θα ηθελες",
//   to_pay: "το παυ?",
//   A_server_will_be_with: "Ένας διακομιστής θα είναι με",
//   you_shortly: "σύντομα.",
//   Staying_at_the_hotel: "Μείνετε στο ξενοδοχείο?",
//   Share_link: "Μοιράζομαι ένα σύνδεσμο",
//   Login: "Σύνδεση",
//   Blend_Menu: "Μενού μείγματος",
//   add_home_screen_message:
//     "Προσθέστε αυτήν την εφαρμογή στην αρχική οθόνη σας για πρόσβαση esay και καλύτερη εμπειρία",
//   Tap: "Παρακέντηση",
//   Add_to_Home_Screen: "και μετά 'Προσθήκη στην αρχική οθόνη'",
//   Checkout: "ολοκλήρωση παραγγελίας",
//   View_menu: "Προβολή μενού",
//   Order: "Σειρά",
//   Order_confirmed: "Η παραγγελία επιβεβαιώθηκε!",
//   Order_confirm_Message:
//     "Η παραγγελία σας έχει επιβεβαιωθεί, για να τη δείτε μεταβείτε στις Προηγούμενες παραγγελίες στην αρχική οθόνη.",
//   Order_declined: "Η παραγγελία απορρίφθηκε",
//   Order_expired: "Η παραγγελία έληξε",
//   Great: "Μεγάλος!",
  
//   Order_expired_message:
//     "Η παραγγελία σας έχει λήξει, για περισσότερες πληροφορίες επικοινωνήστε με τη διεύθυνση.",
//   Order_decline_message:
//     "Η παραγγελία σας απορρίφθηκε, για περισσότερες πληροφορίες επικοινωνήστε με τη διεύθυνση.",
//   Order_decline_kitchen:
//     "Φαίνεται ότι η κουζίνα απέρριψε την παραγγελία σας, για περισσότερες πληροφορίες επικοινωνήστε με τον υπεύθυνο",
//   order_complete_message:
//     "Η παραγγελία σας έχει σταλεί, περιμένοντας τον χώρο να την αποδεχτεί.",
//   Order_number: "Αριθμός παραγγελίας",
//   Pay: "Πληρωμή",
//   card: "κάρτα",
//   payment_message:
//     "Επιλέξτε τον παρακάτω τρόπο πληρωμής, λάβετε υπόψη εάν επιλέξετε μετρητά για να μην έχετε κενό πορτοφόλι!",
//   How_would_you_like_to_pay: "Πώς θα θέλατε να πληρώσετε?",
//   My_Orders: "Οι παραγγελίες μου",
//   Order: "Σειρά",
//   Declined: "Απορρίφθηκε",
//   Accepted: "Αποδεκτό",
//   Not_Paid: "Απληρωτος",
//   Paid: "επί πληρωμή",
//   No_Previous_Order: "Χωρίς προηγούμενη παραγγελία",
//   Payment_failed: "Η πληρωμή απέτυχε",
//   Are_you_sure_you: "Είστε σίγουροι",
//   want_to_exit: "θέλω να βγείτε",
//   No: "Οχι",
//   Your_Tab_has_expired: "Η καρτέλα σας έχει λήξει",
//   About: "Σχετικά με",
//   Add_item: "Πρόσθεσε είδος",
//   Error_404: "Σφάλμα 404",
//   Page_Not_Found: "Η σελίδα δεν βρέθηκε",
//   check_it_out: "Τσέκαρέ το",
//   Search: "Αναζήτηση",
//   Email_sent_Successfully: "Το ηλεκτρονικό ταχυδρομείο στάλθηκε με επιτυχία",
//   Something_went_wrong_Try_Again: "Κάτι πήγε στραβά. Προσπάθησε ξανά",
//   We_have_sent_you_an_email: "Σας στείλαμε ένα email",
//   with_your_session_link: "με τον σύνδεσμο περιόδου σύνδεσης",
//   Go_to_your_inbox: "Μεταβείτε στα εισερχόμενά σας",
//   Send_again: "Στείλε ξανά",
//   Enter_your_table_number: "Εισαγάγετε τον αριθμό του τραπεζιού σας",
//   View_menu_and_order: "Προβολή μενού και παραγγελία",
//   something_went_wrong: "κάτι πήγε στραβά!",
//   Enter_email: "Εισάγετε ηλεκτρονική διεύθυνση",
//   You_will_receive_your_access_link: "Θα λάβετε τον σύνδεσμο πρόσβασης",
//   Enter_email_used_during_check_in: "Εισαγάγετε το email που χρησιμοποιήθηκε κατά το check-in",
//   Enter_email_here: "Εισαγάγετε email εδώ",
//   Invalid_Email: "Ακυρη διεύθυνση ηλεκτρονικού ταχυδρομείου",
//   Field_is_required: "Απαιτείται πεδίο",
//   Send_Email: "Να στείλετε ΗΛΕΚΤΡΟΝΙΚΗ ΔΙΕΥΘΥΝΣΗ",
//   Table_number_or_password_match: "Ο αριθμός πίνακα ή ο κωδικός πρόσβασης δεν ταιριάζουν",
//   Missing_fields: "Λείπουν πεδία",
// };

// export default messages;
