export const NAME = "NAME";
export const AGE = "AGE";
export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";

//MAIN FEATURES (ABID)

export const GET_ALL_FEATURES = "GET_ALL_FEATURES";
export const GET_ALL_SERVICES = "GET_ALL_SERVICES";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_DONATIONS = "GET_ALL_DONATIONS";
export const GET_ALL_HIRES = "GET_ALL_HIRES";
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const SEARCH_USERS = "SEARCH_USERS";
export const ADD_HIRE_USER = "ADD_HIRE_USER";
export const GET_ALL_SENT_REQUEST = "GET_ALL_SENT_REQUEST";
export const GET_ALL_RECIEVE_REQUEST = "GET_ALL_RECIEVE_REQUEST";
export const UPDATE_RECIEVE_REQUESTS_STATUS = "UPDATE_RECIEVE_REQUESTS_STATUS";
export const ADD_DONATION = "ADD_DONATION";
export const GET_ALL_AVAILABLE_DONATIONS = "GET_ALL_AVAILABLE_DONATIONS";
export const UPDATE_DONATION_STATUS = "UPDATE_DONATION_STATUS";


